### ISSUE TITLE
Add conditional and adjust language for Iowa  Code 910.1(A) Affidavit

### ISSUE THREAD

**Issue by amsclark** [amsclark/docassemble-ATPCalculator#5]
If they are in Iowa, it should represent that this is a document they need. If they are not in Iowa, present alternate language that they should check their local rules and statutes for required filings, and that they may look at an Iowa (and later Virginia) as an example.

**Comment by mnmnk43434** [comment]
Hello, we tried to solve the issue.

This is what we did:

Modified the intro.yml file to include a question about whether the user is in Iowa, and added conditional text based on the answer. This addresses the criteria to present different information for Iowa residents versus non-residents.

You can review changes in this commit: https://github.com/mnmnk43434/amsclark-docassemble-ATPCalculator-5/commit/053c9267d98311423e2324529eb0923967fc93d0.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
